apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloservlet-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloservlet-m2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloservlet-varlibcontainers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: helloservlet-pipelineconfig
data:
  dev-image-path: 'image-registry.openshift-image-registry.svc:5000/helloservlet/helloservlet'
  release-image-path: 'quay.io/gmagnotta/helloservlet'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: helloservlet-s2ienvironment
data:
  environment: |
    MAVEN_REPOS="nexus"
    NEXUS_MAVEN_REPO_ID="nexus"
    NEXUS_MAVEN_REPO_URL="http://nexus3:8081"
    MAVEN_SETTINGS_XML="/home/jboss/.m2/settings.xml"
    CUSTOM_INSTALL_DIRECTORIES="extensions"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloservlet-dev-pipeline
spec:
  params:
    - name: repo-url
  workspaces:
    - name: src
    - name: m2
    - name: varlibcontainers
    - name: empty
    - name: s2ienv
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: src
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: get-dev-path
      taskRef:
        name: get-configmap-value
      runAfter:
        - fetch-repository
      params:
        - name: CONFIGMAP-NAME
          value: "helloservlet-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-image-path"
    - name: build
      taskRef:
        name: buildah-s2i
      runAfter:
        - get-dev-path
      workspaces:
        - name: source
          workspace: src
        - name: varlibcontainers
          workspace: varlibcontainers
        - name: artifacts
          workspace: m2
        - name: s2ienv
          workspace: s2ienv
      params:
        - name: S2I_IMAGE
          value: "registry.redhat.io/jboss-webserver-5/jws56-openjdk11-openshift-rhel8"
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(tasks.get-dev-path.results.VALUE)
        - name: CONTEXT
          value: "."
        - name: INCREMENTAL
          value: "true"
    - name: deploy
      taskRef:
        name: openshift-actions
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: src
      params:
        - name: CONTEXT
          value: "."
        - name: SCRIPT
          value: |
            oc process -p IMAGE=$(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST) -p CAUSE=$(tasks.fetch-repository.results.commit) -f helloservlet-template.yaml | oc apply -f -
    - name: update-built-image
      taskRef:
        name: set-configmap-value
      runAfter:
        - deploy
      params:
        - name: CONFIGMAP-NAME
          value: "helloservlet-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image"
        - name: VALUE
          value: $(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloservlet-promote-pipeline
spec:
  params:
    - name: dest-namespace
  workspaces:
    - name: src
  tasks:
    - name: get-image-built
      taskRef:
        name: get-configmap-value
      params:
        - name: CONFIGMAP-NAME
          value: "helloservlet-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image"
    - name: deploy
      taskRef:
        name: openshift-actions
      runAfter:
        - get-image-built
      workspaces:
        - name: source
          workspace: src
      params:
        - name: CONTEXT
          value: "."
        - name: SCRIPT
          value: |
            oc process -p IMAGE=$(tasks.get-image-built.results.VALUE) -p CAUSE=$(tasks.get-image-built.results.VALUE) -f helloservlet-template.yaml | oc apply --namespace=$(params.dest-namespace) -f - 
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloservlet-release-pipeline
spec:
  params:
    - name: image-tag
  workspaces:
    - name: empty
  tasks:
    - name: get-image-built
      taskRef:
        name: get-configmap-value
      params:
        - name: CONFIGMAP-NAME
          value: "helloservlet-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image"
    - name: getpushpath
      taskRef:
        name: get-configmap-value
      params:
        - name: CONFIGMAP-NAME
          value: "helloservlet-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "release-image-path"
    - name: copy
      taskRef:
        name: skopeo-copy
        kind: ClusterTask
      runAfter:
        - getpushpath
        - get-image-built
      workspaces:
        - name: images-url
          workspace: empty
      params:
        - name: srcImageURL
          value: "docker://$(tasks.get-image-built.results.VALUE)"
        - name: destImageURL
          value: "docker://$(tasks.getpushpath.results.VALUE):$(params.image-tag)"
        - name: srcTLSverify
          value: "false"
        - name: destTLSverify
          value: "false"