kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-from-helloservlet
  namespace: integration
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: helloservlet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit

