apiVersion: template.openshift.io/v1
kind: Template
labels:
  mylabel: helloservlet
message: This is an OpenShift template to deploy helloservlet.
metadata:
  name: helloservlet
  annotations:
    description: "helloservlet Template"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: helloservlet
    labels:
      app: hello-servlet
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hello-servlet
    template:
      metadata:
        labels:
          app: hello-servlet
        annotations:
          kubernetes.io/change-cause: ${CAUSE}
      spec:
        containers:
          - name: hello-servlet
            image: ${IMAGE}
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: hello-servlet
    labels:
      app: hello-servlet
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: hello-servlet
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: hello-servlet
    labels:
      app: hello-servlet
  spec:
    to:
      kind: Service
      name: hello-servlet
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
- description: Container image to use
  name: IMAGE
  required: true
- description: Description of this installation
  name: CAUSE
  required: true
