apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Internal OCP registry is located at image-registry.openshift-image-registry.svc:5000
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloservlet-pipeline
spec:
  params:
    - name: repo-url
    - name: image-path
  workspaces:
    - name: myworkspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: myworkspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - fetch-repository
      params:
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(params.image-path)
      workspaces:
        - name: source
          workspace: myworkspace

